# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0003_auto_20180515_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
