# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0004_auto_20180515_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='date',
            field=models.DateField(),
        ),
    ]
