# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 08:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0010_auto_20180515_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='last4digit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
