# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 08:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0011_auto_20180515_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='last4digit',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')]),
        ),
    ]
